---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: rh-sign-image
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: |-
    Task to create internalrequests or pipelineruns to sign snapshot components
  params:
    - name: snapshotPath
      description: Path to the JSON string of the mapped Snapshot spec in the data workspace
      type: string
    - name: dataPath
      description: Path to the JSON string of the merged data to use in the data workspace
      type: string
    - name: releasePlanAdmissionPath
      description: Path to the JSON string of the releasePlanAdmission in the data workspace
      type: string
    - name: requester
      type: string
      description: Name of the user that requested the signing, for auditing purposes
    - name: requestTimeout
      type: string
      default: "1800"
      description: InternalRequest timeout
    - name: pipelineRunUid
      type: string
      description: The uid of the current pipelineRun. Used as a label value when creating internal requests
    - name: ociStorage
      description: The OCI repository where the Trusted Artifacts are stored
      type: string
      default: "empty"
    - name: ociArtifactExpiresAfter
      description: Expiration date for the trusted artifacts created in the
        OCI repository. An empty string means the artifacts do not expire
      type: string
      default: "1d"
    - name: trustedArtifactsDebug
      description: Flag to enable debug logging in trusted artifacts. Set to a non-empty string to enable
      type: string
      default: ""
    - name: orasOptions
      description: oras options to pass to Trusted Artifacts calls
      type: string
      default: ""
    - name: sourceDataArtifact
      type: string
      description: Location of trusted artifacts to be used to populate data directory
      default: ""
    - name: dataDir
      description: The location where data will be stored
      type: string
      default: /var/workdir/release
    - name: taskGitUrl
      type: string
      description: The url to the git repo where the release-service-catalog tasks and stepactions to be used are stored
    - name: taskGitRevision
      type: string
      description: The revision in the taskGitUrl repo to be used
    - name: caTrustConfigMapName
      type: string
      description: The name of the ConfigMap to read CA bundle data from
      default: trusted-ca
    - name: caTrustConfigMapKey
      type: string
      description: The name of the key in the ConfigMap that contains the CA bundle data
      default: ca-bundle.crt
  results:
    - description: Produced trusted data artifact
      name: sourceDataArtifact
      type: string
  volumes:
    - name: workdir
      emptyDir: {}
    - name: trusted-ca
      configMap:
        name: $(params.caTrustConfigMapName)
        items:
          - key: $(params.caTrustConfigMapKey)
            path: ca-bundle.crt
        optional: true

  stepTemplate:
    volumeMounts:
      - mountPath: /var/workdir
        name: workdir
      - name: trusted-ca
        mountPath: /mnt/trusted-ca
        readOnly: true
    securityContext:
      runAsUser: 1001
    env:
      - name: IMAGE_EXPIRES_AFTER
        value: $(params.ociArtifactExpiresAfter)
      - name: "ORAS_OPTIONS"
        value: "$(params.orasOptions)"
      - name: "DEBUG"
        value: "$(params.trustedArtifactsDebug)"
  steps:
    - name: use-trusted-artifact
      computeResources:
        limits:
          memory: 64Mi
          cpu: 30m
        requests:
          memory: 64Mi
          cpu: 30m
      ref:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: stepactions/use-trusted-artifact/use-trusted-artifact.yaml
      params:
        - name: workDir
          value: $(params.dataDir)
        - name: sourceDataArtifact
          value: $(params.sourceDataArtifact)

    - name: sign-image
      image: quay.io/konflux-ci/release-service-utils@sha256:3cb03b14ac9d90ff27070036ce2b50712e65aa285daeb28852254a745bb25dfc
      computeResources:
        limits:
          memory: 512Mi
          cpu: 500m
        requests:
          memory: 512Mi
          cpu: 500m
      script: |
        #!/usr/bin/env bash
        set -ex

        SNAPSHOT_PATH=$(params.dataDir)/$(params.snapshotPath)
        TASK_LABEL="internal-services.appstudio.openshift.io/group-id"
        TASK_ID=$(context.taskRun.uid)
        PIPELINERUN_LABEL="internal-services.appstudio.openshift.io/pipelinerun-uid"

        DATA_FILE="$(params.dataDir)/$(params.dataPath)"
        if [ ! -f "${DATA_FILE}" ] ; then
            echo "No valid data file was provided."
            exit 1
        fi
        RPA_FILE="$(params.dataDir)/$(params.releasePlanAdmissionPath)"
        if [ ! -f "${RPA_FILE}" ] ; then
            echo "No valid rpa file was provided."
            exit 1
        fi

        REQUESTTYPE=$(jq -r '.requestType // "internal-request"' "${DATA_FILE}")
        service_account_name=$(jq -r '.spec.pipeline.serviceAccountName // "release-service-account"' "${RPA_FILE}")
        if [ "${REQUESTTYPE}" == "internal-pipelinerun" ] ; then
          requestType=internal-pipelinerun
          EXTRA_ARGS=(
          --service-account "${service_account_name}"
          )
        else
          requestType=internal-request
          EXTRA_ARGS=()
        fi
        request=$(jq -r '.sign.request // "direct-signing-pipeline"' "${DATA_FILE}")
        config_map_name=$(jq -r '.sign.configMapName // "signing-config-map"' "${DATA_FILE}")

        defaultPushSourceContainer=$(jq -r \
          '.mapping.defaults.pushSourceContainer | if . == null then true else . end' "${DATA_FILE}")

        # Gather signing keys from configmap
        jqquery='.data|if has ("SIG_KEY_NAMES")
        then (.SIG_KEY_NAMES|split(",")|.[]|gsub("^\\s+|\\s+$";"")) else .SIG_KEY_NAME end'
        configMapJson=$(kubectl get "cm/${config_map_name:?}" -ojson)
        SIG_KEY_NAMES=$(jq -er "$jqquery" <<< "${configMapJson}")

        COMPONENTS_LENGTH=$(jq '.components |length' "${SNAPSHOT_PATH}")
        declare -a to_sign_references=()
        declare -a to_sign_digests=()

        for (( i = 0; i < COMPONENTS_LENGTH; i++ )); do
            component=$(jq -c --argjson i "$i" '.components[$i]' "${SNAPSHOT_PATH}")
            referenceContainerImage=$(jq -r '.containerImage' <<< "$component")

            # check if multi-arch
            RAW_OUTPUT=$(skopeo inspect --retry-times 3 --no-tags --raw "docker://${referenceContainerImage}")
            manifest_digests="${referenceContainerImage#*@}"
            MEDIATYPE="$(jq -r '.mediaType' <<< "$RAW_OUTPUT")"
            if [ "$MEDIATYPE" != "application/vnd.oci.image.manifest.v1+json" ] && \
               [ "$MEDIATYPE" != "application/vnd.docker.distribution.manifest.v2+json" ]; then
              nested_digests=$(jq -r '[.manifests[].digest] | join(" ")' <<< "$RAW_OUTPUT")
              manifest_digests="$manifest_digests $nested_digests"
            fi
            echo "MANIFEST DIGESTS: ${manifest_digests}"

            sourceContainerDigest=
            if [[ $(jq -r '.pushSourceContainer' <<< "$component") == "true" ]] || \
               [[ $(jq 'has("pushSourceContainer")' <<< "$component") == "false" \
                && ${defaultPushSourceContainer} == "true" ]] ; then
              source_repo=${referenceContainerImage%%@sha256:*}
              source_reference_tag=sha256-${referenceContainerImage#*@sha256:}.src
              sourceContainer="${source_repo}:${source_reference_tag}"

              AUTH_FILE=$(mktemp)
              select-oci-auth "${sourceContainer}" > "$AUTH_FILE"
              sourceContainerDigest=$(oras resolve --registry-config "$AUTH_FILE" "${sourceContainer}")
            fi

            NUM_REPOS=$(jq -c '.repositories | length' <<< "$component")
            for ((j = 0; j < NUM_REPOS; j++)); do
              repo=$(jq -c --argjson j "$j" '.repositories[$j]' <<< "$component")
              TAGS=$(jq -r '.tags | join(" ")' <<< "$repo")
              rh_registry_repo=$(jq -er '."rh-registry-repo"' <<< "$repo")

              for manifest_digest in $manifest_digests; do
                for tag in ${TAGS}; do
                  to_sign_references+=("${rh_registry_repo}:${tag}")
                  to_sign_digests+=("${manifest_digest}")
                done
              done

              # Source container signing
              if [ "${sourceContainerDigest}" != "" ] ; then
                for tag in ${TAGS}; do
                  to_sign_references+=("${rh_registry_repo}:${tag}-source")
                  to_sign_digests+=("${sourceContainerDigest}")
                done
              fi
            done
        done

        # Create internal-requests with batching
        BATCH_LIMIT=16384
        REQUEST_COUNT=0
        references_batch=""
        digests_batch=""

        for i in "${!to_sign_references[@]}"; do
          reference="${to_sign_references[$i]}"
          digest="${to_sign_digests[$i]}"

          new_references_batch="${references_batch}${reference} "
          new_digests_batch="${digests_batch}${digest} "

          if [[ ${#new_references_batch} -gt $BATCH_LIMIT || ${#new_digests_batch} -gt $BATCH_LIMIT ]]; then
            echo "Creating ${requestType} to sign images: ${references_batch}"
            ${requestType} \
              --pipeline "${request}" \
              -p references="${references_batch}" \
              -p signing_key_names="${SIG_KEY_NAMES}" \
              -p manifest_digests="${digests_batch}" \
              -p requester="$(params.requester)" \
              -p taskGitUrl="$(params.taskGitUrl)" \
              -p taskGitRevision="$(params.taskGitRevision)" \
              -l ${TASK_LABEL}="${TASK_ID}" \
              -l ${PIPELINERUN_LABEL}="$(params.pipelineRunUid)" \
              -t "$(params.requestTimeout)" --pipeline-timeout "0h30m0s" --task-timeout "0h25m0s" \
              "${EXTRA_ARGS[@]}" -s true &
            ((++REQUEST_COUNT))

            references_batch="${reference} "
            digests_batch="${digest} "
          else
            references_batch="${new_references_batch}"
            digests_batch="${new_digests_batch}"
          fi
        done

        # Send remaining batch
        if [[ ${#references_batch} -gt 0 ]]; then
          echo "Creating ${requestType} to sign images: ${references_batch}"
          ${requestType} \
            --pipeline "${request}" \
            -p references="${references_batch}" \
            -p signing_key_names="${SIG_KEY_NAMES}" \
            -p manifest_digests="${digests_batch}" \
            -p requester="$(params.requester)" \
            -p taskGitUrl="$(params.taskGitUrl)" \
            -p taskGitRevision="$(params.taskGitRevision)" \
            -l ${TASK_LABEL}="${TASK_ID}" \
            -l ${PIPELINERUN_LABEL}="$(params.pipelineRunUid)" \
            -t "$(params.requestTimeout)" --pipeline-timeout "0h30m0s" --task-timeout "0h25m0s" \
            "${EXTRA_ARGS[@]}" -s true &
          ((++REQUEST_COUNT))
        fi

        echo "Waiting for ${REQUEST_COUNT} signing requests to complete..."
        wait
        echo "done"

    - name: create-trusted-artifact
      computeResources:
        limits:
          memory: 128Mi
          cpu: 250m
        requests:
          memory: 128Mi
          cpu: 250m
      ref:
        resolver: "git"
        params:
          - name: url
            value: "$(params.taskGitUrl)"
          - name: revision
            value: "$(params.taskGitRevision)"
          - name: pathInRepo
            value: stepactions/create-trusted-artifact/create-trusted-artifact.yaml
      params:
        - name: ociStorage
          value: $(params.ociStorage)
        - name: workDir
          value: $(params.dataDir)
        - name: sourceDataArtifact
          value: $(results.sourceDataArtifact.path)
