---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: direct-signing-pipeline
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: |-
    Tekton pipeline for direct container signing using rh-signing-client.
    It is meant to be used by the rh-sign-image task, not as a standalone
    managed pipeline.
  params:
    - name: manifest_digests
      description: Space separated manifest digests for the signed content
      type: string
    - name: references
      description: >-
        Space separated docker references for the signed content,
        e.g. registry.redhat.io/redhat/community-operator-index:v4.9
      type: string
    - name: requester
      description: Name of the user that requested the signing, for auditing purposes
      type: string
    - name: signing_key_names
      description: Space separated list of signing key names to use
      type: string
    - name: pipeline_image
      description: An image with rh-signing-client needed for the signing
      default: "quay.io/konflux-ci/signing:latest"
      type: string
    - name: config_map_name
      description: A config map name with configuration
      default: hacbs-signing-pipeline-config
      type: string
    - name: taskGitUrl
      description: The url to the git repo where the release-service-catalog tasks to be used are stored
      default: https://github.com/konflux-ci/release-service-catalog.git
      type: string
    - name: taskGitRevision
      description: The revision in the taskGitUrl repo to be used
      type: string
  tasks:
    - name: direct-sign-and-upload
      retries: 2
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: tasks/internal/direct-sign-and-upload/direct-sign-and-upload.yaml
      params:
        - name: manifest_digests
          value: $(params.manifest_digests)
        - name: references
          value: $(params.references)
        - name: requester
          value: $(params.requester)
        - name: sig_key_names
          value: $(params.signing_key_names)
        - name: pipeline_image
          value: $(params.pipeline_image)
